// A curated list of common dish/food names to power autocomplete on the
// "option name" fields. Not exhaustive — just broad enough that typing a
// few letters of something common turns up sensible suggestions.
export const FOOD_SUGGESTIONS: string[] = [
  // chicken
  "Chicken Breast",
  "Chicken Salad",
  "Chicken Salad Sandwich",
  "Chicken Parmesan",
  "Chicken Tikka Masala",
  "Chicken Tenders",
  "Chicken Wings",
  "Buffalo Chicken Wings",
  "Chicken Caesar Salad",
  "Chicken Fried Rice",
  "Chicken Noodle Soup",
  "Chicken Alfredo",
  "Chicken Katsu",
  "Chicken Shawarma",
  "Chicken Quesadilla",
  "Chicken Burrito",
  "General Tso's Chicken",
  "Orange Chicken",
  "Chicken Kebab",
  "Chicken Pot Pie",
  "Fried Chicken",
  "Grilled Chicken Sandwich",
  "Chicken Teriyaki",
  "Chicken Biryani",
  // salads
  "Greek Salad",
  "Cobb Salad",
  "Caesar Salad",
  "Caprese Salad",
  "Garden Salad",
  "Kale Salad",
  "Quinoa Salad",
  "Potato Salad",
  "Pasta Salad",
  "Fruit Salad",
  // pasta / italian
  "Spaghetti Carbonara",
  "Spaghetti Bolognese",
  "Fettuccine Alfredo",
  "Lasagna",
  "Penne Arrabbiata",
  "Margherita Pizza",
  "Pepperoni Pizza",
  "Risotto",
  "Gnocchi",
  "Tiramisu",
  // mexican
  "Beef Tacos",
  "Fish Tacos",
  "Carnitas Tacos",
  "Al Pastor Tacos",
  "Burrito Bowl",
  "Chips and Guacamole",
  "Nachos",
  "Enchiladas",
  "Tamales",
  "Elote",
  // burgers / american
  "Cheeseburger",
  "Bacon Burger",
  "Veggie Burger",
  "BBQ Ribs",
  "Mac and Cheese",
  "Mashed Potatoes",
  "Loaded Fries",
  "Hot Dog",
  "Club Sandwich",
  "Grilled Cheese",
  "Meatloaf",
  // asian
  "Pad Thai",
  "Pho",
  "Ramen",
  "Fried Rice",
  "Dumplings",
  "Spring Rolls",
  "Sushi Rolls",
  "Salmon Nigiri",
  "Tempura",
  "Bibimbap",
  "Korean BBQ",
  "Kung Pao Chicken",
  "Beef and Broccoli",
  "Green Curry",
  "Red Curry",
  "Massaman Curry",
  "Butter Chicken",
  "Paneer Tikka",
  "Samosas",
  "Naan",
  // seafood
  "Grilled Salmon",
  "Shrimp Scampi",
  "Fish and Chips",
  "Clam Chowder",
  "Lobster Roll",
  "Crab Cakes",
  "Poke Bowl",
  // breakfast / brunch
  "Pancakes",
  "Waffles",
  "French Toast",
  "Avocado Toast",
  "Chilaquiles",
  "Breakfast Burrito",
  "Eggs Benedict",
  "Omelette",
  "Bagel and Lox",
  "Shakshuka",
  // desserts
  "Cheesecake",
  "Chocolate Cake",
  "Brownies",
  "Ice Cream Sundae",
  "Apple Pie",
  "Churros",
  "Creme Brulee",
  "Donuts",
];
